### ISSUE TITLE
Natures aren't being imported from Team-Converter

### ISSUE THREAD

**Issue by SamTheSwan** [pmariglia/showdown#24] opened 2019-12-13 20:05 UTC
Errors in line 125, 126 of team_converter.py, boolean is never coming out as true when importing teams directly from showdown team import/export. Tried 'Nature', ' Nature', 'Nature ', and ' Nature '.

**Comment by pmariglia** [comment] 2019-12-14 13:52
Hi, could you please provide the export file you are having difficulties with, preferably in markdown format.

Self-Note:
I really should (somehow) integrate the PokemonShowdown Client exporter. Just going to link it [here ](https://github.com/smogon/pokemon-showdown-client/blob/e1fe420402b398e3feb36a039493046a7ed0b0af/js/storage.js#L1063)for future me

**Comment by pmariglia** [comment] 2020-04-04 21:13
Closing this as it has been over 3 months with no reply and I am unable to reproduce this specific issue.

There are problems with the team-converter, however natures specifically seem to be properly captured. This is tested [here](https://github.com/pmariglia/showdown/blob/b15feec3a6010b2a1a5d6ba07b713abd65b06d5d/tests/test_team_converter.py#L144)

**Closed by pmariglia** 2020-04-04 21:13 UTC
