### ISSUE TITLE
Due to spam from your internet provider, You can't challenge others right now. Logging into an account you've used a lot in the past will allow you to challenge.

### ISSUE THREAD

**Issue by link-discord** [pmariglia/showdown#45] opened 2020-11-05 23:01 UTC
When using the bot for a while it gets muted for spam

Due to spam from your internet provider, you can't challenge others right now. Logging into an account you've used a lot in the past will allow you to challenge.

possibly the bot is being rate limited or something

**Comment by pmariglia** [comment] 2020-11-06 22:35
I've seen this myself as well.

Doesn't seem to affect my same machine going through the browser so the PS server must be detecting that a bot is running. I can reach out in the PS smogon discord when I get a chance and see if anyone can provide some context.

Accepting challenges and searching the ladder still seem to function normally.

**Comment by LINKdiscordd** [comment] 2020-11-06 22:42
maybe make an option to disable the greeting and ending message

because staff told me the server sees the bot as a potential spam bot

**Comment by pmariglia** [comment] 2020-11-06 23:07
I could totally do that - but I'm surprised that one simple "hf" and "gg" could trigger that?

Since the same machine can use the browser normally the server must be using some other mechanism to detect the bot

**Comment by LINKdiscordd** [comment] 2020-11-07 07:20
Maybe talk about some of the PS tech staff about this

**Comment by LINKdiscordd** [comment] 2020-11-07 07:21
Wasn't just the bot though
when that happened it was for my browser too untill I logged back into my auto confirmed account

**Comment by LINKdiscordd** [comment] 2020-11-07 07:21
The bot didn't got the semilock removed though if I did the same

**Comment by pcwoodford** [comment] 2020-11-12 16:52
I created a new account and tried running it through a vpn with the comments about gg and hf taken out and that doesn't seem to be the fix. However I might have to have those accounts for longer periods of time first.

**Comment by pmariglia** [comment] 2021-09-20 00:52
I'm going to close this since nothing can be done from the perspective of this code, and I haven't seen this issue in awhile.

The folks in the smogon development discord claim that an account must be "autoconfirmed" for this to not show up, which means:
- the account must be 1 week old
- the account must win 1 ladder battle

My account was both of those things when I received the error, but it eventually stopped. It's possible there was a temporary flaw in the PS server code that checked this, but who knows.

**Closed by pmariglia** 2021-09-20 00:52 UTC
