### ISSUE TITLE
directing the bot to localhost

### ISSUE THREAD

**Issue by OmaeKumiko** [pmariglia/showdown#16] opened 2019-11-12 13:01 UTC
Hi pmariglia, I much appreciate your effort in making this project. Lately I attempted to test it on my local showdown server by editing the WEBSOCKET_URI item in .env to be localhost:xxxx, but the bot would still connect to the default port sim.smogon.com:8000. Which module should I edit to fix this?

**Comment by pmariglia** [comment] 2019-11-12 14:13
Hi, thanks for the kind words :)

That's interesting - I've used a local showdown server many times without any problems. 

Could you provide the .env file you are using? If it's connecting to sim.smogon.com it means that the environment variable isn't being set.

**Comment by pmariglia** [comment] 2019-12-08 03:31
I've been unable to reproduce this & have had no problems connecting to a local showdown server using the following line in my .env file:
```
WEBSOCKET_URI=localhost:8000
```

Closing this for now. If you continue to experience this problem please feel free to re-open this issue.

**Closed by pmariglia** 2019-12-08 03:31 UTC
