### ISSUE TITLE
Issue with building from docker

### ISSUE THREAD

**Issue by zuils** [pmariglia/showdown#132] opened 2022-10-26 22:29 UTC
```
[+] Building 0.0s (2/2) FINISHED
 => ERROR [internal] load build definition from Dockerfile                                                         0.0s
 => ERROR [internal] load .dockerignore                                                                            0.0s
------
 > [internal] load build definition from Dockerfile:
------
------
 > [internal] load .dockerignore:
------
failed to solve with frontend dockerfile.v0: failed to read dockerfile: failed to create lease: write /var/lib/docker/buildkit/containerdmeta.db: read-only file system
```
Tried with and without a virtual environment and got this error, don't know what the issue is.

**Comment by pmariglia** [comment] 2022-10-29 18:11
Is this the entire log? 

I've built from scratch on both Linux (20.10.12) and OSX (20.10.17) using Docker desktop (4.12.0) and can't reproduce. This might be an issue with your docker setup.

**Comment by zuils** [comment] 2022-10-30 18:57
> Is this the entire log? 
> 
> 
> 
> I've built from scratch on both Linux (20.10.12) and OSX (20.10.17) using Docker desktop (4.12.0) and can't reproduce. This might be an issue with your docker setup.

Yes, tried it with windows and WSL Ubuntu 20.04

**Comment by Zelow202** [comment] 2022-11-08 14:02
I am getting a similar error on Windows Docker Desktop version 4.13.1. 
docker build . -t showdown
[+] Building 0.0s (2/2) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 2B                                                                                 0.0s
 => CANCELED [internal] load .dockerignore                                                                         0.0s
 => => transferring context:                                                                                       0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount3936251531/Dockerfile: no such file or directory

**Comment by pmariglia** [comment] 2023-07-09 17:09
Closing as I cannot reproduce

Please re-open if you have better reproduction steps

**Closed by pmariglia** 2023-07-09 17:09 UTC
