### ISSUE TITLE
Bot uses ground move on pokemon with levitate

### ISSUE THREAD

**Issue by LINKdiscordd** [pmariglia/showdown#47] opened 2020-11-12 17:12 UTC
I had a pokemon with earthquake and it used earthquake on a rotom with levitate
but all the next turns it used that same move again and again and again
even though the other pokemon had levitate

**Comment by LINKdiscordd** [comment] 2020-11-12 17:14
Add a check if the pokemon has the levitate ability and then prevent it from choosing a ground type move

**Comment by pmariglia** [comment] 2020-11-12 20:47
Do you have a log of the battle? It's really hard to say what the bot was thinking in your particular scenario without one.

Logic to identify that earthquake does nothing against levitate is definitely implemented in the engine. [Here is a test for that scenario](https://github.com/pmariglia/showdown/blob/2230dc09f7ecef45770173c13e4d00066eec95a8/tests/test_get_state_instructions.py#L10493).

Unless there is a bug setting the levitate ability, which I cannot determine without a battle-log, what likely happened is that for whatever reason the minimax algorithm saw earthquake was the best move. This is a feature - not a bug.

Its bad, for sure. But I never claimed that this bot was the best :)

**Comment by pmariglia** [comment] 2020-12-18 20:37
Closing for now. If you have logs showing something wrong with the bot please feel free to re-open

**Closed by pmariglia** 2020-12-18 20:37 UTC
