### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by SomeRandomGuy009** [pmariglia/showdown#142] opened 2022-12-16 15:20 UTC
Traceback (most recent call last):
  File "/workspaces/showdown/run.py", line 93, in <module>
    asyncio.get_event_loop().run_until_complete(showdown())
  File "/home/somerandomguy/.python/current/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/workspaces/showdown/run.py", line 78, in showdown
    winner = await pokemon_battle(ps_websocket_client, ShowdownConfig.pokemon_mode)
  File "/workspaces/showdown/showdown/run_battle.py", line 217, in pokemon_battle
    best_move = await async_pick_move(battle)
  File "/workspaces/showdown/showdown/run_battle.py", line 37, in async_pick_move
    best_move = await loop.run_in_executor(
  File "/home/somerandomguy/.python/current/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/workspaces/showdown/showdown/battle_bots/team_datasets/main.py", line 191, in find_best_move
    return format_decision(self, safest_move)
  File "/workspaces/showdown/showdown/battle_bots/helpers.py", line 42, in format_decision
    if battle.user.active.get_move(decision).can_z:
AttributeError: 'NoneType' object has no attribute 'can_z'

**Comment by SomeRandomGuy009** [comment] 2022-12-16 15:21
has happened only once. If this didn't happen, the bot would have been in top 500s gen9 ou, most likely the 70th battle

**Comment by pmariglia** [comment] 2022-12-17 20:25
Thanks for the report @SomeRandomGuy009, that's great to hear about the performance.

Unfortunately, gen9 isn't completely supported yet so stuff like this is bound to happen while I figure out all of the issues. Do you have the logs leading up to this crash? Or at least the teams that were used in this battle? Unfortunately I can't do much just based on this error.

**Comment by SomeRandomGuy009** [comment] 2022-12-18 13:57
> Thanks for the report @SomeRandomGuy009, that's great to hear about the performance.
> 
> Unfortunately, gen9 isn't completely supported yet so stuff like this is bound to happen while I figure out all of the issues. Do you have the logs leading up to this crash? Or at least the teams that were used in this battle? Unfortunately I can't do much just based on this error.

Thanks. The team i used is in the example gen 9 team PR

**Comment by SomeRandomGuy009** [comment] 2022-12-18 13:59
Sadly, no logs.

**Comment by SomeRandomGuy009** [comment] 2022-12-21 12:55
same thing happened again. here is the battle id.

https://replay.pokemonshowdown.com/gen9ou-1749317693
Iris0 is the bot btw

and last message before crash was this:
[DEBUG]    Safest: splash, 817.0

**Comment by pmariglia** [comment] 2022-12-22 00:04
Thanks for the additional info. I'll try to reproduce when I get a chance.

**Comment by pmariglia** [comment] 2022-12-23 18:05
Looking at that battle it seems likely that this is because of Revival Blessing - something that has not been implemented yet.

To know for sure I'd need a more complete log from the bot - probably the last several lines, especially the one that spits out the state the bot thinks it is searching through before and after revival blessing is used.

Regardless, implementing revival blessing is something that needs to be done for gen9 compatibility.

**Comment by pmariglia** [comment] 2022-12-23 20:30
b47c9fcd18faaebe653613ea2cba2b15886259d2 implements revivalblessing parsing for when the opponent uses the move.

If this was the cause of the crash it should be fixed. I'll leave this issue open for a little while - please add another comment if you see this issue happen again.

**Comment by SomeRandomGuy009** [comment] 2022-12-24 02:49
Thanks, I'll check and let you know

**Comment by SomeRandomGuy009** [comment] 2022-12-26 08:10
Works, no issues. Looks like the bug has been fixed.

**Comment by pmariglia** [comment] 2022-12-26 16:46
Thanks. I'll close this for now.

**Closed by pmariglia** 2022-12-26 16:46 UTC
